### ISSUE TITLE
Associate purchased domain with main Netlify deployment 

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#63]
# Overview

Domain and DNS information are not currently available.

Target date contract milestone production release is 1/29/21.

Netlify deployment: https://gender-survey-dashboard.netlify.app/

**Comment by dboyer** [comment]
Domain to purchase is www.equalityathome.org

**Comment by dboyer** [comment]
If possible, it would be useful to purchase this week so they can set up Analytics.

**Comment by hectcastro** [comment]
Are they purchasing the domain and providing us with a way to modify DNS (either by asking them or giving us access to do it ourselves), or are we purchasing the domain ourselves?

**Comment by dboyer** [comment]
They would like us to purchase the domain and actually included that specifically in the Scope of Work. It's easier for paperwork purposes for them.

**Comment by hectcastro** [comment]
@dboyer Things are tentatively wired up to the state of the site as reflected by the `master` branch: https://www.equalityathome.org/ We will have to create a release (or merge `develop` into `master`) in order for it to look like the [staging instance](https://600b200554079d00073865d8--gender-survey-dashboard.netlify.app/) of the site.

cc: @rcheetham because I purchased the domain via Name.com earlier today.

**Comment by dboyer** [comment]
Thanks - we're hoping to soft launch next week so I don't think it matters that the site doesn't match staging. I'll confirm with the client on our call today.

**Comment by mmcfarland** [comment]
@TaiWilkin and I will cut a release near the end of the week to get the production branch updated. There will likely be quick additional releases after that for small changes before the full launch.
